#!/usr/bin/env python3
"""Regenerate INDEX.md from the frontmatter of principles/*.md.

The index is the only file read on a normal session, so it must never be stale.
A hand-maintained index would drift; this makes drift impossible.

Usage: python3 meta/architecture-learning/reindex.py
"""

import glob
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FIELDS = ("id", "kind", "type", "confidence", "evidence", "updated")


def parse(path):
    """Extract frontmatter and the first heading from one principle file."""
    meta, heading = {}, ""
    with open(path) as handle:
        lines = handle.read().splitlines()
    if not lines or lines[0].strip() != "---":
        sys.exit(f"{path}: missing frontmatter")
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            body = lines[i + 1:]
            break
        if ":" in line:
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    else:
        sys.exit(f"{path}: unterminated frontmatter")
    for line in body:
        if line.startswith("# "):
            heading = line[2:].strip()
            break
    missing = [f for f in FIELDS if f not in meta]
    if missing:
        sys.exit(f"{path}: frontmatter missing {', '.join(missing)}")
    meta["statement"] = heading or "(no heading)"
    meta["file"] = os.path.basename(path)
    return meta


def main():
    entries = [parse(p) for p in sorted(glob.glob(os.path.join(HERE, "principles", "*.md")))]
    if not entries:
        sys.exit("no principle files found")

    by_kind = {}
    for entry in entries:
        by_kind.setdefault(entry["kind"], []).append(entry)

    out = [
        "# Index",
        "",
        "Generated by `reindex.py` — do not edit by hand.",
        "",
        "This is the routing table, and the only file that needs reading on a normal",
        "session. To decide whether a new observation is evidence for an existing",
        "principle or a new one, read this; then open at most one principle file.",
        "",
        f"{len(entries)} principles, "
        f"{sum(int(e['evidence']) for e in entries)} pieces of evidence.",
        "",
    ]
    for kind in ("architectural", "working"):
        rows = by_kind.get(kind, [])
        if not rows:
            continue
        label = {"architectural": "Architectural positions",
                 "working": "Working preferences"}[kind]
        out += [f"## {label}", "",
                "| statement | confidence | type | evidence | file |",
                "|---|---|---|---|---|"]
        for e in sorted(rows, key=lambda r: (-int(r["evidence"]), r["id"])):
            out.append(
                f"| {e['statement']} | {e['confidence']} | {e['type']} | "
                f"{e['evidence']} | [`{e['file']}`](principles/{e['file']}) |"
            )
        out.append("")

    unknown = set(by_kind) - {"architectural", "working"}
    if unknown:
        out += [f"> Unrecognised `kind` values, not listed above: "
                f"{', '.join(sorted(unknown))}", ""]

    with open(os.path.join(HERE, "INDEX.md"), "w") as handle:
        handle.write("\n".join(out))
    print(f"wrote INDEX.md — {len(entries)} principles")


if __name__ == "__main__":
    main()
